# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
  
[[main]]
  name = "Story"
  url = "#story"
  weight = 10

[[main]]
  name = "Mechanics"
  url = "#mechanics"
  weight = 20
  
  [[main]]
  name = "Items"
  url = "#items"
  weight = 30
  
  [[main]]
  name = "Boss battles"
  url = "#boss"
  weight = 40
  
    [[main]]
  name = "Game modes"
  url = "#modes"
  weight = 50

    [[main]]
  name = "Challenges"
  url = "#Challenges"
  weight = 60
  
#[[main]]
#  name = ""
#  url = "#posts"
#  weight = 20

#[[main]]
#  name = ""
#  url = "#projects"
#  weight = 30

#[[main]]
#  name = "Publications"
#  url = "#featured"
#  weight = 40

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
